### PR TITLE
Task #30291:

### PR DESCRIPTION
**Pull request by eberglundhs**
- Add Discussing page.

### CODE REVIEW

**Comment by rphovley** [comment]
screen shot 2018-07-31 at 10 43 00 am
I think there's a bit more padding between the header and the content on the designs

**Comment by rphovley** [comment]
screen shot 2018-07-31 at 10 43 09 am

I would take the references component out of your primary-container div as the references component already has that as part of it's styling

**Comment by rphovley** [comment]
Looks good! Let me know what you think about the comments above

**Comment by dantalbert** [comment]
As far as the padding below the main header goes, I added it to the shared classes so this should be fixed when my stuff gets merged in.

**Pull request merged**
